[project]
author = "Subhajit Das"
name = "smart-commit"
url = "https://github.com/0verread/smart-commit"
version = "1.0.0"

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel"]

[project.scripts]
scommit = "smart-commit.smartcommit:main"